 DROP TABLE IF EXISTS DRONE;
 CREATE TABLE DRONE(
 id INT AUTO_INCREMENT PRIMARY KEY,
 serial INT(100) NOT NULL,
 model VARCHAR(50) NOT NULL,
 weight_limit VARCHAR(20) NOT NULL,
 battery_capacity VARCHAR(10) NOT NULL,
 state VARCHAR(100) NOT NULL
 );

 DROP TABLE IF EXISTS DRONE_LOADED;
 CREATE TABLE DRONE_LOADED(
 id INT AUTO_INCREMENT PRIMARY KEY,
 drone_id INT(100)  NOT NULL,
 name VARCHAR(50) NOT NULL,
 weight VARCHAR(10) NOT NULL,
 code VARCHAR(10) NOT NULL,
 image VARCHAR(1000) NOT NULL
 );
